####     _     _             _ _
##      | |   (_)           (_) |
##      | |    _  __ _ _   _ _| |__   __ _ ___  ___
##      | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \
##      | |___| | (_| | |_| | | |_) | (_| \__ \  __/
##      \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|
##                  | |
##                  |_|
##
####

changeLogFile=src\main\resources\dbchangelog.h2.sql
liquibase.command.url=jdbc:h2:C:/Users/adity/Desktop/taskflow/data/db
liquibase.command.username: sa
liquibase.command.password: 

# 
# NOTES ::
# liquibase generate-changelog --changelog-file=src\main\resources\dbchangelog.h2.sql
# liquibase changelog-sync --changelog-file=src\main\resources\datachangelog.h2.sql
# 
# 
# liquibase clearCheckSums
# CALL CSVWRITE('PROJECT_MEMBER .csv', 'SELECT * FROM PROJECT_MEMBER ');
