export enum NotificationEventEnum {
    TASK_CREATED = 'TASK_CREATED',
    TASK_UPDATED = 'TASK_UPDATED',
    TASK_DELETED = 'TASK_DELETED',
    PROJECT_CREATED = 'PROJECT_CREATED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',
    PROJECT_DELETED = 'PROJECT_DELETED',
    COMMENT_ADDED = 'COMMENT_ADDED',
    COMMENT_DELETED = 'COMMENT_DELETED',
    MEMBER_CHANGED = 'MEMBER_CHANGED',
    MEMBER_DELETED = 'MEMBER_DELETED'
}