spring.application.name=taskflow
spring.datasource.url=jdbc:h2:file:./data/db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# spring.liquibase.change-log=classpath:db/changelog/dbchangelog.sql  
spring.liquibase.change-log=classpath:db.changelog-master.xml  
spring.liquibase.enabled=true
spring.jpa.open-in-view=false
spring.main.allow-circular-references=false
spring.cache.type=simple
#"Do NOT treat my repositories as Redis repositories"
spring.data.redis.repositories.enabled=false



#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.springframework.cache=TRACE
